"""Builds the emitted LocalSettings fragment and the generated seed report.

The config fragment is the D3/D4 contract: instance-specific entity ids keyed
by *label-derived* keys, never hardcoded in extension code. The seed resolves
labels to ids via the API and emits this file for inclusion from
LocalSettings.php.

License: GPL-2.0-or-later
"""

from __future__ import annotations

from typing import Any

# Property label (en) -> short kind used in the config map.
PROPERTY_KINDS = {
    "content text": ("payloadProperties", "quotation"),
    "code source": ("payloadProperties", "code"),
    "LaTeX source": ("payloadProperties", "math"),
    "programming language": ("programmingLanguage", None),
    "attributed to": ("provenance", "attributedTo"),
    "source URL": ("provenance", "sourceUrl"),
    "source": ("provenance", "source"),
    "date": ("provenance", "date"),
}
CLASS_KINDS = {
    "quotation content": "quotation",
    "code snippet": "code",
    "mathematical expression": "math",
}


def build_config(
    property_ids: dict[str, str],
    class_ids: dict[str, str],
    lexer_ids: dict[str, str],
    fallback_languages: list[str],
) -> str:
    """Returns a PHP snippet assigning $wgEmbeddableContentConfig and the
    Wikibase settings the seed is responsible for."""

    classes: dict[str, str] = {}
    payload: dict[str, str] = {}
    for label, kind in CLASS_KINDS.items():
        if label in class_ids:
            classes[kind] = class_ids[label]

    payload_props: dict[str, str] = {}
    provenance: dict[str, str] = {}
    programming_language = None
    for label, (section, key) in PROPERTY_KINDS.items():
        if label not in property_ids:
            continue
        prop_id = property_ids[label]
        if section == "payloadProperties":
            payload_props[key] = prop_id
        elif section == "provenance":
            provenance[key] = prop_id
        elif section == "programmingLanguage":
            programming_language = prop_id

    config: dict[str, Any] = {
        "instanceOf": property_ids.get("instance of"),
        "classes": classes,
        "payloadProperties": payload_props,
        "programmingLanguage": programming_language,
        "provenance": provenance,
        "fallbackLanguages": fallback_languages,
        "lexers": dict(sorted(lexer_ids.items())),
    }
    config = {k: v for k, v in config.items() if v not in (None, {}, [])}

    lines = [
        "<?php",
        "// Generated by seed/seed_instance.py (issue #6, D2) — do not edit by hand.",
        "// Re-run the seed after changing the vocabulary manifests.",
        "",
        "$wgEmbeddableContentConfig = " + php_array(config, indent="\t") + ";",
        "",
        "// Wikibase settings emitted by the seed (issue #6, §2):",
        "$wgWBRepoSettings['string-limits']['VT:monolingualtext']['length'] = 50000;",
        "$wgWBRepoSettings['string-limits']['VT:string']['length'] = 50000;",
        "$wgWBClientSettings['wellKnownReferencePropertyIds'] = "
        + php_array(
            {
                "referenceUrl": property_ids.get("source URL"),
                "statedIn": property_ids.get("source"),
                "author": property_ids.get("attributed to"),
                "publicationDate": property_ids.get("date"),
            },
            indent="\t",
        )
        + ";",
        "$wgWikibaseCitationInstanceOf = " + php_scalar(property_ids.get("instance of")) + ";",
        "$wgWBRepoSettings['sandboxEntityIds'] = [ 'mainItem' => 'Q999999998', 'auxItem' => 'Q999999999' ];",
        "$wgWBRepoSettings['dataRightsUrl'] = 'https://creativecommons.org/publicdomain/zero/1.0/';",
        "$wgWBRepoSettings['rdfDataRightsUrl'] = 'https://creativecommons.org/publicdomain/zero/1.0/';",
        "",
    ]
    return "\n".join(line for line in lines if "=> None" not in line and "=>null" not in line)


def build_report(
    property_ids: dict[str, str],
    class_ids: dict[str, str],
    lexer_ids: dict[str, str],
    dogfood_ids: dict[str, str],
    languages: list[str],
) -> str:
    """Returns the seed report as MediaWiki wikitext (self-documenting docs)."""
    lines = [
        "The '''ronzz-wikibase seed report''' documents the vocabulary created by the",
        "one-time bootstrap (issue #6, D2). Re-generated on every seed run.",
        "",
        "Instance languages: " + ", ".join(f"''{lang}''" for lang in languages) + "",
        "",
        "== Properties ==",
        '{| class="wikitable"',
        "! Label (en) !! Entity",
    ]
    for label in sorted(property_ids):
        lines.append(f"| {label} || {property_ids[label]}")
    lines += ["|}", "", "== Classes ==", '{| class="wikitable"', "! Label (en) !! Entity"]
    for label in sorted(class_ids):
        lines.append(f"| {label} || {class_ids[label]}")
    lines += ["|}", "", "== Programming languages ==", '{| class="wikitable"', "! Lexer !! Entity"]
    for lexer in sorted(lexer_ids):
        lines.append(f"| {lexer} || {lexer_ids[lexer]}")
    lines += ["|}", "", "== Dogfood entities ==", '{| class="wikitable"', "! Kind !! Entity"]
    for kind in sorted(dogfood_ids):
        lines.append(f"| {kind} || {dogfood_ids[kind]}")
    lines += [
        "|}",
        "",
        "== Config map ==",
        "The emitted <code>$wgEmbeddableContentConfig</code> is generated from the",
        "IDs above; see <code>seed/generated/</code> for the LocalSettings fragment.",
        "",
    ]
    return "\n".join(lines)


def php_array(data: Any, indent: str = "\t", level: int = 0) -> str:
    """Serializes a dict/list into a PHP array literal (single-quoted strings)."""
    pad = indent * level
    inner_pad = indent * (level + 1)
    if isinstance(data, dict):
        if not data:
            return "[]"
        items = []
        for key, value in data.items():
            k = php_scalar(key)
            v = php_array(value, indent, level + 1) if isinstance(value, (dict, list)) else php_scalar(value)
            items.append(f"{inner_pad}{k} => {v},")
        return "[\n" + "\n".join(items) + f"\n{pad}]"
    if isinstance(data, list):
        if not data:
            return "[]"
        items = [f"{inner_pad}{php_scalar(value)}," for value in data]
        return "[\n" + "\n".join(items) + f"\n{pad}]"
    return php_scalar(data)


def php_scalar(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, int):
        return str(value)
    escaped = str(value).replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"
