<?php

declare( strict_types = 1 );

namespace EmbeddableContent;

use InvalidArgumentException;

/**
 * Typed access to the `$wgEmbeddableContentConfig` map emitted by the seed
 * (D2). The map is instance-specific — entity ids are never hardcoded in
 * extension code (issue #6, §1.4).
 *
 * Expected shape (generated by seed/config_builder.py):
 * [
 *   'instanceOf'          => 'P31',
 *   'classes'             => [ 'quotation' => 'Q1', 'code' => 'Q2', 'math' => 'Q3' ],
 *   'payloadProperties'   => [ 'quotation' => 'P2', 'code' => 'P3', 'math' => 'P4' ],
 *   'programmingLanguage' => 'P5',
 *   'provenance'          => [ 'attributedTo' => 'P6', 'sourceUrl' => 'P7', 'source' => 'P8', 'date' => 'P9' ],
 *   'fallbackLanguages'   => [ 'fr', 'en', 'eo' ],
 *   'lexers'              => [ 'python' => 'Q10', 'cpp' => 'Q11' ],
 * ]
 *
 * @license GPL-2.0-or-later
 */
class EmbeddableContentConfig {

	public const KINDS = [ 'quotation', 'code', 'math' ];

	/** @var array<string,mixed> */
	private $raw;

	/**
	 * @param array<string,mixed> $raw
	 * @throws InvalidArgumentException when the map is not a usable config
	 */
	public function __construct( array $raw ) {
		$this->raw = $raw;
		$this->assertShape();
	}

	public function instanceOfPropertyId(): string {
		return $this->requireString( 'instanceOf' );
	}

	/** @return array<string,string> kind => item id */
	public function classIds(): array {
		return $this->requireStringMap( 'classes', self::KINDS );
	}

	/** @return array<string,string> kind => property id */
	public function payloadPropertyIds(): array {
		return $this->requireStringMap( 'payloadProperties', self::KINDS );
	}

	public function programmingLanguagePropertyId(): string {
		return $this->requireString( 'programmingLanguage' );
	}

	/** @return array<string,string> canonical provenance key => property id */
	public function provenancePropertyIds(): array {
		$allowed = [ 'attributedTo', 'sourceUrl', 'source', 'date' ];
		return $this->requireStringMap( 'provenance', $allowed );
	}

	/** @return string[] */
	public function fallbackLanguages(): array {
		$value = $this->raw['fallbackLanguages'] ?? [];
		if ( !is_array( $value ) ) {
			throw new InvalidArgumentException( 'EmbeddableContentConfig: fallbackLanguages must be a list' );
		}
		return array_values( array_filter( $value, 'is_string' ) );
	}

	/** @return array<string,string> lexer name => language item id */
	public function lexerItemIds(): array {
		$value = $this->raw['lexers'] ?? [];
		if ( !is_array( $value ) ) {
			throw new InvalidArgumentException( 'EmbeddableContentConfig: lexers must be a map' );
		}
		$result = [];
		foreach ( $value as $lexer => $id ) {
			if ( is_string( $lexer ) && is_string( $id ) ) {
				$result[$lexer] = $id;
			}
		}
		return $result;
	}

	/**
	 * Returns the lexer name for a language item id, or null.
	 */
	public function lexerForItemId( string $itemId ): ?string {
		foreach ( $this->lexerItemIds() as $lexer => $id ) {
			if ( $id === $itemId ) {
				return $lexer;
			}
		}
		return null;
	}

	/** @return string[] */
	private function requireStringMap( string $key, array $allowedKeys ): array {
		$value = $this->raw[$key] ?? [];
		if ( !is_array( $value ) ) {
			throw new InvalidArgumentException( "EmbeddableContentConfig: $key must be a map" );
		}
		$result = [];
		foreach ( $allowedKeys as $allowed ) {
			if ( isset( $value[$allowed] ) ) {
				if ( !is_string( $value[$allowed] ) ) {
					throw new InvalidArgumentException( "EmbeddableContentConfig: $key.$allowed must be a string" );
				}
				$result[$allowed] = $value[$allowed];
			}
		}
		return $result;
	}

	private function requireString( string $key ): string {
		$value = $this->raw[$key] ?? null;
		if ( !is_string( $value ) || $value === '' ) {
			throw new InvalidArgumentException( "EmbeddableContentConfig: missing or invalid '$key'" );
		}
		return $value;
	}

	private function assertShape(): void {
		$this->instanceOfPropertyId();
		$this->classIds();
		$this->payloadPropertyIds();
		$this->programmingLanguagePropertyId();
		$this->provenancePropertyIds();
		$this->fallbackLanguages();
	}
}
