<?php

declare( strict_types = 1 );

namespace EmbeddableContent;

use InvalidArgumentException;

/**
 * Typed access to the `$wgEmbeddableContentConfig` map emitted by the seed
 * (D2). The map is instance-specific — entity ids are never hardcoded in
 * extension code (issue #6, §1.4).
 *
 * Expected shape (generated by seed/config_builder.py):
 * [
 *   'instanceOf'          => 'P31',
 *   'classes'             => [ 'quotation' => 'Q1', 'code' => 'Q2', 'math' => 'Q3' ],
 *   'payloadProperties'   => [ 'quotation' => 'P2', 'code' => 'P3', 'math' => 'P4' ],
 *   'programmingLanguage' => 'P5',
 *   'provenance'          => [ 'attributedTo' => 'P6', 'sourceUrl' => 'P7', 'source' => 'P8', 'date' => 'P9' ],
 *   'sourceClasses'       => [ 'book' => 'Q9', 'scholarlyArticle' => 'Q10', … ],
 *   'fossClasses'         => [ 'foss' => 'Q16' ],
 *   'fossProperties'      => [ 'developer' => 'P33', 'license' => 'P34', … ],
 *   'fallbackLanguages'   => [ 'fr', 'en', 'eo' ],
 *   'lexers'              => [ 'python' => 'Q10', 'cpp' => 'Q11' ],
 * ]
 *
 * @license GPL-2.0-or-later
 */
class EmbeddableContentConfig {

	public const KINDS = [ 'quotation', 'code', 'math' ];

	/** @var array<string,mixed> */
	private $raw;

	/**
	 * @param array<string,mixed> $raw
	 * @throws InvalidArgumentException when the map is not a usable config
	 */
	public function __construct( array $raw ) {
		$this->raw = $raw;
		$this->assertShape();
	}

	public function instanceOfPropertyId(): string {
		return $this->requireString( 'instanceOf' );
	}

	/** @return array<string,string> kind => item id */
	public function classIds(): array {
		return $this->requireStringMap( 'classes', self::KINDS );
	}

	/** @return array<string,string> kind => property id */
	public function payloadPropertyIds(): array {
		return $this->requireStringMap( 'payloadProperties', self::KINDS );
	}

	public function programmingLanguagePropertyId(): string {
		return $this->requireString( 'programmingLanguage' );
	}

	/**
	 * Content-subject property for mathematical expressions ('describes').
	 * Nullable: absent on instances seeded before this property existed.
	 */
	public function describesPropertyId(): ?string {
		return $this->optionalString( 'describes' );
	}

	/**
	 * Content-subject property for code snippets ('implementation of').
	 * Nullable: absent on instances seeded before this property existed.
	 */
	public function implementationOfPropertyId(): ?string {
		return $this->optionalString( 'implementationOf' );
	}

	/** @return array<string,string> canonical provenance key => property id */
	public function provenancePropertyIds(): array {
		$allowed = [ 'attributedTo', 'sourceUrl', 'source', 'date' ];
		return $this->requireStringMap( 'provenance', $allowed );
	}

	/** @return string[] */
	public function fallbackLanguages(): array {
		$value = $this->raw['fallbackLanguages'] ?? [];
		if ( !is_array( $value ) ) {
			throw new InvalidArgumentException( 'EmbeddableContentConfig: fallbackLanguages must be a list' );
		}
		return array_values( array_filter( $value, 'is_string' ) );
	}

	/** @return array<string,string> lexer name => language item id */
	public function lexerItemIds(): array {
		$value = $this->raw['lexers'] ?? [];
		if ( !is_array( $value ) ) {
			throw new InvalidArgumentException( 'EmbeddableContentConfig: lexers must be a map' );
		}
		$result = [];
		foreach ( $value as $lexer => $id ) {
			if ( is_string( $lexer ) && is_string( $id ) ) {
				$result[$lexer] = $id;
			}
		}
		return $result;
	}

	/**
	 * Returns the lexer name for a language item id, or null.
	 */
	public function lexerForItemId( string $itemId ): ?string {
		foreach ( $this->lexerItemIds() as $lexer => $id ) {
			if ( $id === $itemId ) {
				return $lexer;
			}
		}
		return null;
	}

	/**
	 * Issue #7: authority ExternalId property ids (Special:AddPerson etc.).
	 *
	 * @return array<string,string> canonical key => property id (absent keys omitted)
	 */
	public function externalIdPropertyIds(): array {
		return $this->requireStringMap( 'externalIds', [
			'wikidata', 'orcid', 'viaf', 'isni', 'doi', 'isbn', 'openalex', 'pubmed',
			// Person OpenAlex author id (P5092-aligned "OpenAlex author ID").
			'openalexAuthor',
		] );
	}

	/**
	 * Issue #7: citation-metadata property ids (full harvest statements).
	 *
	 * @return array<string,string> canonical key => property id
	 */
	public function citationMetadataPropertyIds(): array {
		return $this->requireStringMap( 'citationMetadata', [
			'givenName', 'familyName', 'publishedIn', 'publisher', 'pages', 'volume', 'issue',
			// Entity-typed journal (P1433-aligned "journal (entity)").
			'journal',
		] );
	}

	/**
	 * Known license items (label => item id) emitted by the seed from the
	 * preseed license vocabulary — the review-form license combobox options
	 * (Special:Upload-style: pick from the list, or type to search).
	 * Absent on instances seeded without preseed licenses: the combobox
	 * falls back to entity search only.
	 *
	 * @return array<string,string>
	 */
	public function licenseItems(): array {
		return $this->optionalStringMap( 'licenses' );
	}

	/**
	 * Person lifecycle property ids (Special:AddPerson statements): date of
	 * birth / death (time), place of birth / death (wikibase-item), and the
	 * portrait facts — `image` (url, P18-aligned) + `license`
	 * (wikibase-item, P275-aligned, shared with the FOSS/access vocab).
	 * Absent keys are omitted (instance-specific availability).
	 *
	 * @return array<string,string> canonical key => property id
	 */
	public function personPropertyIds(): array {
		return $this->requireStringMap( 'personProperties', [
			'dateOfBirth', 'placeOfBirth', 'dateOfDeath', 'placeOfDeath',
			'image', 'license',
		] );
	}

	/**
	 * Issue #7: source/work class ids (Special:AddSource class picker).
	 *
	 * @return array<string,string> canonical key => item id
	 */
	public function sourceClasses(): array {
		return $this->requireStringMap( 'sourceClasses', [
			'book', 'scholarlyArticle', 'website', 'song', 'film', 'video',
			'youtubeChannel', 'youtubeVideo', 'webpage', 'bookExcerpt',
		] );
	}

	/**
	 * Issue #7: source-class parent/child map (child class key => parent
	 * class key). Child-class creation requires an existing parent-class
	 * item, picked on the form and linked via the `part of` statement.
	 *
	 * @return array<string,string>
	 */
	public function sourceParents(): array {
		return $this->optionalStringMap( 'sourceParents' );
	}

	/**
	 * Property id of the child→parent link statement (`part of`), from the
	 * sourceProperties map; null when the instance predates it.
	 */
	public function sourceParentPropertyId(): ?string {
		return $this->sourcePropertyIds()['partOf'] ?? null;
	}

	/**
	 * Issue #7: source-class specific property ids (Special:AddSource
	 * statements): partOf, duration, url, youtubeChannelId, youtubeVideoId,
	 * chapters. Issue #35 adds the access field keys: license (shared with
	 * the FOSS vocabulary), accessUrl, file. Absent keys are omitted
	 * (instance-specific availability).
	 *
	 * @return array<string,string> canonical key => property id
	 */
	public function sourcePropertyIds(): array {
		return $this->requireStringMap( 'sourceProperties', [
			'partOf', 'duration', 'url', 'youtubeChannelId', 'youtubeVideoId', 'chapters',
			'license', 'accessUrl', 'file',
		] );
	}

	/**
	 * YouTube Data API v3 key for the YouTube provider (deploy-injected via
	 * the instance environment — never committed to the repo). Empty string
	 * disables the provider.
	 */
	public function youtubeApiKey(): string {
		$value = $this->raw['youtubeApiKey'] ?? '';
		return is_string( $value ) ? $value : '';
	}

	/**
	 * YouTube search-list result cache TTL in seconds (0 = disabled, the
	 * default at this instance's scale). A config flip, not a code change,
	 * if repeat-query quota ever matters.
	 */
	public function youtubeSearchCacheTtl(): int {
		$value = $this->raw['youtubeSearchCacheTtl'] ?? 0;
		return is_int( $value ) ? $value : (int)$value;
	}

	/**
	 * Issue #7: agent class ids (Special:AddPerson / AddCollective).
	 *
	 * @return array<string,string> canonical key => item id
	 */
	public function agentClasses(): array {
		return $this->requireStringMap( 'agentClasses', [
			'person', 'organization', 'groupOfHumans',
			'privateCompany', 'publicCompany', 'nonProfitOrganization',
			'governmentalAgency', 'musicBand', 'educationalInstitution',
			'researchInstitute', 'politicalParty', 'tradeUnion',
			'religiousOrganization', 'sportsTeam',
		] );
	}

	/**
	 * Issue #7: Wikidata QID → local source-class key (harvest class inference).
	 *
	 * @return array<string,string>
	 */
	public function sourceClassByWikidata(): array {
		return $this->optionalStringMap( 'sourceClassByWikidata' );
	}

	/**
	 * Issue #7: Wikidata QID → local agent-class key (harvest class inference).
	 *
	 * @return array<string,string>
	 */
	public function agentClassByWikidata(): array {
		return $this->optionalStringMap( 'agentClassByWikidata' );
	}

	/**
	 * Issue #26: FOSS software class ids (Special:AddSoftware class picker).
	 *
	 * @return array<string,string> canonical key => item id
	 */
	public function fossClasses(): array {
		return $this->requireStringMap( 'fossClasses', [ 'foss' ] );
	}

	/**
	 * Issue follow-up: fictional-character class ids
	 * (Special:AddFictionalCharacter).
	 *
	 * @return array<string,string> canonical key => item id
	 */
	public function fictionalCharacterClasses(): array {
		return $this->requireStringMap( 'fictionalCharacterClasses', [ 'fictionalCharacter' ] );
	}

	/**
	 * Issue follow-up: fictional-character property ids
	 * (Special:AddFictionalCharacter statements): the multi-value
	 * `present in work` ("appears in") link.
	 *
	 * @return array<string,string> canonical key => property id
	 */
	public function fictionalCharacterPropertyIds(): array {
		return $this->requireStringMap( 'fictionalCharacterProperties', [ 'appearsIn' ] );
	}

	/**
	 * Issue #26: FOSS software property ids (Special:AddSoftware statements).
	 *
	 * @return array<string,string> canonical key => property id
	 */
	public function fossPropertyIds(): array {
		return $this->requireStringMap( 'fossProperties', [
			'developer', 'license', 'operatingSystem', 'officialWebsite',
			'sourceRepository', 'softwareVersion', 'hasUse', 'replaces',
			'userInterface', 'documentationUrl', 'image',
		] );
	}

	/**
	 * Issue #7: `formatter URL` property id, or null when not configured.
	 */
	public function formatterUrlPropertyId(): ?string {
		$value = $this->raw['formatterUrl'] ?? null;
		return is_string( $value ) && $value !== '' ? $value : null;
	}

	/**
	 * Lenient string=>string map getter (no key filtering — e.g. the
	 * QID→class-key inference maps).
	 *
	 * @return array<string,string>
	 */
	private function optionalStringMap( string $key ): array {
		$value = $this->raw[$key] ?? [];
		if ( !is_array( $value ) ) {
			throw new InvalidArgumentException( "EmbeddableContentConfig: $key must be a map" );
		}
		$result = [];
		foreach ( $value as $mapKey => $mapValue ) {
			if ( is_string( $mapKey ) && is_string( $mapValue ) ) {
				$result[$mapKey] = $mapValue;
			}
		}
		return $result;
	}

	private function requireStringMap( string $key, array $allowedKeys ): array {
		$value = $this->raw[$key] ?? [];
		if ( !is_array( $value ) ) {
			throw new InvalidArgumentException( "EmbeddableContentConfig: $key must be a map" );
		}
		$result = [];
		foreach ( $allowedKeys as $allowed ) {
			if ( isset( $value[$allowed] ) ) {
				if ( !is_string( $value[$allowed] ) ) {
					throw new InvalidArgumentException( "EmbeddableContentConfig: $key.$allowed must be a string" );
				}
				$result[$allowed] = $value[$allowed];
			}
		}
		return $result;
	}

	private function requireString( string $key ): string {
		$value = $this->raw[$key] ?? null;
		if ( !is_string( $value ) || $value === '' ) {
			throw new InvalidArgumentException( "EmbeddableContentConfig: missing or invalid '$key'" );
		}
		return $value;
	}

	private function optionalString( string $key ): ?string {
		$value = $this->raw[$key] ?? null;
		return is_string( $value ) && $value !== '' ? $value : null;
	}

	private function assertShape(): void {
		$this->instanceOfPropertyId();
		$this->classIds();
		$this->payloadPropertyIds();
		$this->programmingLanguagePropertyId();
		$this->provenancePropertyIds();
		$this->fallbackLanguages();
	}
}
